# Generated by Django 5.0.6 on 2025-07-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_timepost_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="timepost",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
